version: '3'

services:

  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  workspace:
    image: workspace
    build: ./
    volumes:
      - ./workspace:/var/www/html
    ports:
      - "8080:80"
    links:
      - mysql
    tty: true

# ローカルでメールサーバーを使いたいときには以下のコメントアウトを外す
#  mailhog:
#    image: mailhog/mailhog
#    ports:
# - "8025:8025"
# - "1025:1025"
